param(
    [int]$TopN = 20,
    [ValidateSet("lp_max_drawdown_pct","lp_volatility_abs_mean","total_shocks","lp_apy")]
    [string]$SortBy = "lp_max_drawdown_pct"
)

# Generate mock LP data if none exists
if (-not (Get-Variable -Name lpObjects -Scope 0 -ErrorAction SilentlyContinue)) {
    $lpObjects = @(
        [PSCustomObject]@{ lp_name="LP-A"; lp_max_drawdown_pct=5.2; lp_volatility_abs_mean=2.1; total_shocks=3; lp_apy=12.5 }
        [PSCustomObject]@{ lp_name="LP-B"; lp_max_drawdown_pct=0; lp_volatility_abs_mean=0; total_shocks=0; lp_apy=0 }
        [PSCustomObject]@{ lp_name="LP-C"; lp_max_drawdown_pct=7.8; lp_volatility_abs_mean=3.4; total_shocks=5; lp_apy=8.9 }
    )
}

# Check for LP data
if (-not $lpObjects -or $lpObjects.Count -eq 0) {
    Write-Host "⚠️ No LP data generated by simulation." -ForegroundColor Yellow
    return
}

# Top N selection
$top = $lpObjects | Sort-Object $SortBy -Descending | Select-Object -First $TopN

# Call the dashboard
$dashboardPath = if ($PSScriptRoot) {
    Join-Path -Path $PSScriptRoot -ChildPath "scripts\Show-LP-Dashboard.ps1"
} else {
    ".\scripts\Show-LP-Dashboard.ps1"
}

if (Test-Path $dashboardPath) {
    . $dashboardPath -TopN $TopN -SortBy $SortBy
} else {
    Write-Host "❌ Dashboard script not found at $dashboardPath" -ForegroundColor Red
}
